# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'правила',
                'verbose_name_plural': 'Правила использования приложения',
            },
        ),
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(blank=True, null=True, upload_to='bordereau/')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'бордеро',
                'verbose_name_plural': 'Бордеро',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('euro', models.FloatField(null=True)),
                ('usd', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'курсы валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
