# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('euro', models.FloatField(null=True)),
                ('usd', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'курсы валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
