# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='bordereau/'),
        ),
    ]
