# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='insure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
    ]
