# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20160514_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
