# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import profiles.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', profiles.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('create_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, verbose_name='Пол')),
                ('surname_rus', models.CharField(max_length=50, verbose_name='Фамилия на русском')),
                ('name_rus', models.CharField(max_length=50, verbose_name='Имя на русском')),
                ('midname_rus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('passport_int', models.CharField(max_length=50, verbose_name='Номер загранпаспорта')),
                ('surname_eng', models.CharField(max_length=50, verbose_name='Фамилия на английском')),
                ('name_eng', models.CharField(max_length=50, verbose_name='Имя на английском')),
                ('name', models.CharField(max_length=150, verbose_name='название профиля')),
            ],
            options={
                'verbose_name': 'дополнительный профиль',
                'verbose_name_plural': 'Дополнительные профили',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('create_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, verbose_name='Пол')),
                ('surname_rus', models.CharField(max_length=50, verbose_name='Фамилия на русском')),
                ('name_rus', models.CharField(max_length=50, verbose_name='Имя на русском')),
                ('midname_rus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('passport_int', models.CharField(max_length=50, verbose_name='Номер загранпаспорта')),
                ('surname_eng', models.CharField(max_length=50, verbose_name='Фамилия на английском')),
                ('name_eng', models.CharField(max_length=50, verbose_name='Имя на английском')),
                ('use_password', models.BooleanField(default=False, verbose_name='Использовать пароль на клиент?')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=30, verbose_name='Телефон')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Подпись (файл)')),
                ('passport_rf', models.CharField(max_length=50, verbose_name='Номер пасспорта РФ')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('region', models.CharField(max_length=100, verbose_name='регион')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('bld_number', models.CharField(max_length=10, verbose_name='дом')),
                ('bld_letter', models.CharField(blank=True, default='', max_length=10, verbose_name='строение\\литера')),
                ('bld_child', models.CharField(blank=True, default='', max_length=10, verbose_name='корпус')),
                ('apartment', models.CharField(max_length=10, verbose_name='квартира')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
