# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, verbose_name='Пол')),
                ('surname_rus', models.CharField(max_length=50, verbose_name='Фамилия на русском')),
                ('name_rus', models.CharField(max_length=50, verbose_name='Имя на русском')),
                ('midname_rus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('passport_int', models.CharField(max_length=50, verbose_name='Номер загранпаспорта')),
                ('surname_eng', models.CharField(max_length=50, verbose_name='Фамилия на английском')),
                ('name_eng', models.CharField(max_length=50, verbose_name='Имя на английском')),
                ('name', models.CharField(max_length=150, verbose_name='название профиля')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, verbose_name='Пол')),
                ('surname_rus', models.CharField(max_length=50, verbose_name='Фамилия на русском')),
                ('name_rus', models.CharField(max_length=50, verbose_name='Имя на русском')),
                ('midname_rus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('passport_int', models.CharField(max_length=50, verbose_name='Номер загранпаспорта')),
                ('surname_eng', models.CharField(max_length=50, verbose_name='Фамилия на английском')),
                ('name_eng', models.CharField(max_length=50, verbose_name='Имя на английском')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль на клиент')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, verbose_name='Телефон')),
                ('signature', models.FileField(upload_to='upload/', verbose_name='Подпись (файл)')),
                ('passport_rf', models.CharField(max_length=50, verbose_name='Номер пасспорта РФ')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('region', models.CharField(max_length=100, verbose_name='регион')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('bld_number', models.CharField(max_length=10, verbose_name='дом')),
                ('bld_letter', models.CharField(blank=True, default='', max_length=10, verbose_name='строение\\литера')),
                ('bld_child', models.CharField(blank=True, default='', max_length=10, verbose_name='корпус')),
                ('apartment', models.CharField(max_length=10, verbose_name='квартира')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='промо-код')),
                ('latest_action', models.DateTimeField(blank=True, null=True, verbose_name='последние действие')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
