# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_latest_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalprofile',
            name='create_addr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='create_addr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
