# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:37
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160528_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, verbose_name='Телефон'),
        ),
    ]
