# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160520_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.BooleanField(default=True, verbose_name='Используется пароль на клиент'),
        ),
    ]
