# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160520_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='use_password',
            field=models.BooleanField(default=False, verbose_name='Использовать пароль на клиент?'),
        ),
    ]
