# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160528_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='Подпись (файл)'),
        ),
    ]
