# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160529_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='promo_code',
        ),
    ]
