# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:39
from __future__ import unicode_literals

from django.db import migrations
import profiles.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_promo_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', profiles.managers.CustomUserManager()),
            ],
        ),
    ]
