# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20160505_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('status', models.CharField(choices=[('на рассмотрении', 'на рассмотрении'), ('отказано', 'отказано')], max_length=20, verbose_name='Cтатус рассмотрения случая')),
                ('user_comment', models.TextField(blank=True, max_length=600, null=True)),
                ('admin_comment', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('upcoming', 'upcoming'), ('canceled', 'canceled')], max_length=15, verbose_name='Cтатус полиса')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('activation_date', models.DateField(verbose_name='Дата активации полиса')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия полиса')),
                ('sum', models.FloatField()),
                ('insure_type', models.CharField(choices=[('ВЗР', 'ВЗР'), ('ИФЛ', 'ИФЛ')], max_length=3, verbose_name='тип страхования')),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('запрошен', 'запрошен'), ('создан', 'создан'), ('загружен на клиент', 'загружен на клиент')], max_length=25, verbose_name='статус доставки')),
                ('pdf', models.URLField()),
                ('jpg', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Полисы',
                'verbose_name': 'полис',
            },
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.Policy'),
        ),
    ]
