# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFLPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'ИФЛ',
                'verbose_name': 'ифл',
            },
        ),
        migrations.CreateModel(
            name='InsuredAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('create_coords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты места создания')),
                ('status', models.CharField(choices=[('на рассмотрении', 'на рассмотрении'), ('отказано', 'отказано')], max_length=20, verbose_name='Cтатус рассмотрения случая')),
                ('user_comment', models.TextField(blank=True, max_length=600, null=True)),
                ('admin_comment', models.TextField(blank=True, max_length=600, null=True)),
                ('additional_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.AdditionalProfile')),
            ],
            options={
                'verbose_name_plural': 'Страховые случаи',
                'verbose_name': 'страховой случай',
            },
        ),
        migrations.CreateModel(
            name='InsuredProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название собсвенности')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('region', models.CharField(max_length=100, verbose_name='регион')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('bld_letter', models.CharField(blank=True, default='', max_length=10, verbose_name='строение\\литера')),
                ('bld_child', models.CharField(blank=True, default='', max_length=10, verbose_name='корпус')),
                ('apartment', models.CharField(max_length=10, verbose_name='квартира')),
            ],
            options={
                'verbose_name_plural': 'Застрахованная собственность',
                'verbose_name': 'застрахованная собственность',
            },
        ),
        migrations.CreateModel(
            name='NSPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'НЗ',
                'verbose_name': 'нз',
            },
        ),
        migrations.CreateModel(
            name='PolicyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('upcoming', 'upcoming'), ('canceled', 'canceled')], max_length=15, verbose_name='Cтатус полиса')),
                ('create_addr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес создания')),
                ('create_coords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты места создания')),
                ('activation_date', models.DateField(verbose_name='Дата начала действия полиса')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия полиса')),
                ('insure_type', models.CharField(max_length=70, verbose_name='тип страхования')),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('запрошен', 'запрошен'), ('создан', 'создан'), ('загружен на клиент', 'загружен на клиент')], max_length=25, verbose_name='статус доставки')),
                ('pdf', models.URLField()),
                ('jpg', models.URLField()),
                ('exchange_rate', models.FloatField(null=True)),
                ('cost_val', models.FloatField()),
                ('cost_rub', models.FloatField()),
                ('cost_total', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Полисы',
                'verbose_name': 'полис',
            },
        ),
        migrations.CreateModel(
            name='PolicyInsured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_profiles', models.ManyToManyField(blank=True, to='profiles.AdditionalProfile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('Открыто', 'Открыто'), ('В работе', 'В работе'), ('Закрыто', 'Закрыто')], default='Открыто', max_length=20, verbose_name='Cтатус запроса')),
                ('text', models.TextField(max_length=600, null=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name_plural': 'Запрос изменений',
                'verbose_name': 'запрос изменений',
            },
        ),
        migrations.CreateModel(
            name='VZRPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(default='Весь Мир', max_length=20, verbose_name='территория действия')),
                ('sport', models.BooleanField(default=False)),
                ('insured', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyInsured')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase')),
            ],
            options={
                'verbose_name_plural': 'ВЗР',
                'verbose_name': 'взр',
            },
        ),
        migrations.AddField(
            model_name='nspolicy',
            name='insured',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyInsured'),
        ),
        migrations.AddField(
            model_name='nspolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='iflpolicy',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
    ]
