# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinsured',
            name='additional_profiles',
            field=models.ManyToManyField(blank=True, to='profiles.AdditionalProfile'),
        ),
        migrations.AlterField(
            model_name='policyinsured',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
