# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuredaccident',
            options={'verbose_name': 'страховой случай', 'verbose_name_plural': 'Страховые случаи'},
        ),
    ]
