# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchanges',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='policyinsured',
            name='additional_profiles',
            field=models.ManyToManyField(blank=True, to='profiles.AdditionalProfile'),
        ),
        migrations.AddField(
            model_name='policyinsured',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='policybase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='nspolicy',
            name='insured',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyInsured'),
        ),
        migrations.AddField(
            model_name='nspolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='additional_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.AdditionalProfile'),
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
        migrations.AddField(
            model_name='insuredaccident',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='iflpolicy',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
    ]
