# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20160514_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredaccident',
            name='create_addr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
