# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20160531_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policybase',
            name='jpg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policybase',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
