# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20160511_0111'),
        ('profiles', '0002_auto_20160505_0202'),
        ('policies', '0002_auto_20160505_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Полисы',
                'verbose_name': 'полис',
            },
        ),
        migrations.CreateModel(
            name='IFLPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'ИФЛ',
                'verbose_name': 'ифл',
            },
        ),
        migrations.CreateModel(
            name='InsuredProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название собсвенности')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('region', models.CharField(max_length=100, verbose_name='регион')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('bld_letter', models.CharField(blank=True, default='', max_length=10, verbose_name='строение\\литера')),
                ('bld_child', models.CharField(blank=True, default='', max_length=10, verbose_name='корпус')),
                ('apartment', models.CharField(max_length=10, verbose_name='квартира')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('upcoming', 'upcoming'), ('canceled', 'canceled')], max_length=15, verbose_name='Cтатус полиса')),
                ('create_coords', models.CharField(max_length=100, verbose_name='Координаты места создания')),
                ('activation_date', models.DateField(verbose_name='Дата начала действия полиса')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия полиса')),
                ('insure_type', models.CharField(max_length=70, verbose_name='тип страхования')),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('запрошен', 'запрошен'), ('создан', 'создан'), ('загружен на клиент', 'загружен на клиент')], max_length=25, verbose_name='статус доставки')),
                ('pdf', models.URLField()),
                ('jpg', models.URLField()),
                ('cost_val', models.FloatField()),
                ('cost_rub', models.FloatField()),
                ('cost_total', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Полисы',
                'verbose_name': 'полис',
            },
        ),
        migrations.CreateModel(
            name='VZRPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(default='Весь Мир', max_length=20, verbose_name='территория действия')),
                ('sport', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase')),
            ],
            options={
                'verbose_name_plural': 'ВЗР',
                'verbose_name': 'взр',
            },
        ),
        migrations.RemoveField(
            model_name='policy',
            name='owner',
        ),
        migrations.AlterField(
            model_name='insuredaccident',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.AddField(
            model_name='iflpolicy',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='policies.InsuredProperty'),
        ),
    ]
