# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_remove_insuredaccident_create_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='policybase',
            name='activate_addr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес активации'),
        ),
        migrations.AddField(
            model_name='policybase',
            name='activate_coords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты активации'),
        ),
    ]
