# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_requestchanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='NZPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase')),
            ],
            options={
                'verbose_name': 'нз',
                'verbose_name_plural': 'НЗ',
            },
        ),
        migrations.AddField(
            model_name='iflpolicy',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.PolicyBase'),
        ),
    ]
