# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_auto_20160511_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NZPolicy',
            new_name='NSPolicy',
        ),
    ]
