# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_auto_20160613_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policybase',
            name='cost_total',
        ),
        migrations.AddField(
            model_name='iflpolicy',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.InsuredProperty'),
        ),
        migrations.AlterField(
            model_name='insuredproperty',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='insuredproperty',
            name='bld_child',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='корпус'),
        ),
        migrations.AlterField(
            model_name='insuredproperty',
            name='bld_letter',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='строение\\литера'),
        ),
        migrations.AlterField(
            model_name='insuredproperty',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='policybase',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Владелец'),
        ),
    ]
