# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('policies', '0006_auto_20160614_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyinsured',
            name='additional_profiles',
        ),
        migrations.RemoveField(
            model_name='policyinsured',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='nspolicy',
            name='insured',
        ),
        migrations.RemoveField(
            model_name='vzrpolicy',
            name='insured',
        ),
        migrations.AddField(
            model_name='nspolicy',
            name='insured_list',
            field=models.ManyToManyField(blank=True, to='profiles.AdditionalProfile'),
        ),
        migrations.AddField(
            model_name='vzrpolicy',
            name='insured_list',
            field=models.ManyToManyField(blank=True, to='profiles.AdditionalProfile'),
        ),
        migrations.AddField(
            model_name='vzrpolicy',
            name='owner_insured',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PolicyInsured',
        ),
    ]
