# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_auto_20160615_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspolicy',
            name='owner_insured',
            field=models.BooleanField(default=True),
        ),
    ]
