# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=600, null=True)),
                ('status', models.CharField(choices=[('Открыто', 'Открыто'), ('В работе', 'В работе'), ('Закрыто', 'Закрыто')], default='Открыто', max_length=20, verbose_name='Cтатус обращения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
